/**
 * Sift edge Worker.
 *
 * Serves the generated feeds and records opens. It does no curation: the
 * pipeline runs elsewhere (Node, with Readability and SQLite) and pushes
 * finished feed documents here with `npm run push`.
 *
 * Why the split: Workers cannot run this pipeline. `node:sqlite` and `node:vm`
 * are non-functional stubs in the Workers runtime, so neither the database nor
 * jsdom/Readability works — and container disks on Cloudflare are ephemeral, so
 * SQLite has nowhere to live. Putting only the read path at the edge keeps
 * extraction quality intact and still gives you an always-on feed URL that works
 * when the machine running the pipeline is asleep.
 *
 * KV holds the feed XML (read often, written rarely). D1 holds open events
 * (append-only rows, queried by timestamp).
 */

/**
 * KV and D1 bindings come from worker-configuration.d.ts, generated by
 * `wrangler types` from wrangler.toml. Only the secret is declared here,
 * because wrangler cannot know about secrets.
 */
export interface SiftEnv extends Env {
  /** Same token as the Node side. Gates feeds and the events endpoint. */
  SIFT_ACCESS_TOKEN: string;
}

function unauthorized(): Response {
  // 404 rather than 401: an unguessable URL should not confirm it exists.
  return new Response('Not found', { status: 404 });
}

function authorised(request: Request, env: SiftEnv): boolean {
  if (!env.SIFT_ACCESS_TOKEN) return true; // unset = open, for local dev only
  const url = new URL(request.url);
  return url.searchParams.get('t') === env.SIFT_ACCESS_TOKEN;
}

export default {
  async fetch(request: Request, env: SiftEnv): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    if (request.method !== 'GET' && request.method !== 'HEAD') {
      return new Response('Method not allowed', { status: 405 });
    }

    // --- health ------------------------------------------------------------
    if (path === '/health') {
      const pushedAt = await env.SIFT_FEEDS.get('meta:pushed_at');
      return Response.json({
        ok: true,
        lastPushAt: pushedAt ? Number(pushedAt) : null,
        // How stale the feeds are. If this grows, the pipeline is not running.
        stalenessMinutes: pushedAt ? Math.round((Date.now() - Number(pushedAt)) / 60_000) : null,
      });
    }

    // --- generated feeds ---------------------------------------------------
    const feedMatch = /^\/feed\/([a-z0-9-]+)\.(xml|atom|rss|json)$/i.exec(path);
    if (feedMatch) {
      if (!authorised(request, env)) return unauthorized();
      const [, slug, ext] = feedMatch;
      const key = ext === 'rss' ? `feed:${slug}:rss` : ext === 'json' ? `feed:${slug}:json` : `feed:${slug}`;
      const body = await env.SIFT_FEEDS.get(key);
      if (body === null) return new Response('Feed not found', { status: 404 });
      return new Response(body, {
        headers: {
          'content-type': ext === 'rss'
            ? 'application/rss+xml; charset=utf-8'
            : ext === 'json'
              ? 'application/feed+json; charset=utf-8'
              : 'application/atom+xml; charset=utf-8',
          // Reeder polls often; the pipeline only updates every 90 minutes.
          'cache-control': 'public, max-age=600',
        },
      });
    }

    // --- tracked opens -----------------------------------------------------
    // Not token-gated: the reader app follows these links directly, and adding
    // the token here would leak it to publishers via the Referer header.
    const openMatch = /^\/open\/([A-Za-z0-9_-]{8,})$/.exec(path);
    if (openMatch) {
      const itemId = openMatch[1]!;
      const target = await env.SIFT_FEEDS.get(`item:${itemId}`);
      if (!target) return new Response('Unknown item', { status: 404 });

      const feedId = url.searchParams.get('feed');
      // Recording must never delay or block the redirect.
      try {
        await env.SIFT_DB.prepare(
          `INSERT INTO open_events (id, item_id, feed_id, original_url, opened_at)
           VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT(id) DO NOTHING`,
        )
          // One open per item per feed per day, matching the Node side, so
          // re-reading cannot inflate the signal.
          .bind(
            `${itemId}:${feedId ?? ''}:${new Date().toISOString().slice(0, 10)}`,
            itemId,
            feedId,
            target,
            Date.now(),
          )
          .run();
      } catch {
        /* a failed insert is not worth failing the redirect over */
      }

      return new Response(null, {
        status: 302,
        headers: {
          location: target,
          // Keep our URLs, and the reading they imply, out of publisher logs.
          'referrer-policy': 'no-referrer',
          'cache-control': 'no-store',
        },
      });
    }

    // --- events, for the pipeline to pull back ------------------------------
    if (path === '/events') {
      if (!authorised(request, env)) return unauthorized();
      const since = Number(url.searchParams.get('since') ?? 0) || 0;
      const { results } = await env.SIFT_DB.prepare(
        `SELECT id, item_id, feed_id, original_url, opened_at FROM open_events
         WHERE opened_at > ?1 ORDER BY opened_at ASC LIMIT 5000`,
      )
        .bind(since)
        .all();
      return Response.json({ events: results ?? [] });
    }

    if (path === '/') {
      if (!authorised(request, env)) return unauthorized();
      const index = await env.SIFT_FEEDS.get('meta:index');
      return new Response(index ?? 'No feeds pushed yet. Run `npm run push`.', {
        headers: { 'content-type': 'text/plain; charset=utf-8' },
      });
    }

    return new Response('Not found', { status: 404 });
  },
};
